openapi: 3.0.0
info:
  title: sample_api
  version: "1.0"
servers:
  - url: "http://localhost:3000" # base.ts に関係
paths:
  "/hello":
    post:
      summary: サンプル関数
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./models.yml#/Hello"
              # $ref: "#/components/schemas/Hello"
              # $ref: './model.yml#/ItemImagesResponseModel'
        description: "hello"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      name:
                        type: string
      operationId: hello-func
      description: ""
      tags:
        - user
components:
  schemas:
    Hello:
      type: object
      properties:
        name:
          type: string

  # '/users/{user_id}':
  #   parameters:
  #     - schema:
  #         type: string
  #       name: user_id
  #       in: path
  #       required: true
  #   get:
  #     summary: ユーザー取得
  #     responses:
  #       '200':
  #         description: OK
  #         content:
  #           application/json:
  #             schema:
  #               type: object
  #               properties:
  #                 user:
  #                   type: object
  #                   properties:
  #                     name:
  #                       type: string
  #     operationId: get-user_id
  #     description: ''
  #     tags:
  #      - user
  # post:
  #   summary: ユーザー更新
  #   operationId: post-users-user_id
  #   responses:
  #     '200':
  #       description: OK
  #       content:
  #         application/json:
  #           schema:
  #             type: object
  #             properties:
  #               user:
  #                 type: object
  #                 properties:
  #                   name:
  #                     type: string
  #   requestBody:
  #     content:
  #       application/json:
  #         schema:
  #           type: object
  #           properties:
  #             user:
  #               type: object
  #               properties:
  #                 name:
  #                   type: string
  #                 email:
  #                   type: string
  #       application/xml:
  #         schema:
  #           type: object
  #           properties:
  #             user:
  #               type: object
  #               properties:
  #                 name:
  #                   type: string
  #     description: ''
